"""empty message

Revision ID: 507395b2a598
Revises: c34feb4abf9f
Create Date: 2020-07-06 14:02:51.247028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507395b2a598'
down_revision = 'c34feb4abf9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
